name: Daily build
on:
  schedule:
  - cron: "0 1 * * *"

jobs:
  trigger-docker-hub-automated-build:
    runs-on: ubuntu-latest
    steps:
    - name: Post to trigger URL
      run: curl -X POST https://hub.docker.com/api/build/v1/source/69288f5a-6161-44ac-a985-79122d185368/trigger/95afde9f-98c0-4f7a-9aed-6e0b3ab2ec2f/call/
